### ISSUE TITLE
consider making the tree view hierarchy flexible

### ISSUE THREAD

**Issue by jandersen** [cooperhewitt/Planetary#102]
For music collections where artist isn't an efficient sorting criteria consider using something else at the top-level, or making if user configurable.

**Comment by RandomEtc** [comment]
See also #85 about grouping Various Artists

**Comment by RandomEtc** [comment]
See also #148 about grouping by AlbumArtist

**Comment by RandomEtc** [comment]
Moving to wishlist on wiki.
