### ISSUE TITLE
make some screenshots for the app store

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#110]
iPad Screenshots must be .jpeg, .jpg, .tif, .tiff, or .png file that is 1024x768, 1024x748, 768x1024, or 768x1004 pixes, at least 72 DPI, and in the RGB color space.

**Comment by nebster** [comment]
i just started screen capping, but then remembered I don't have the new build with the refined atmosphere geometry yet.  waiting until Robert gets in.

**Comment by RandomEtc** [comment]
Done and done!
