### ISSUE TITLE
make sure we're ok with the standard EULA

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#111]
Here: http://www.apple.com/legal/itunes/appstore/dev/stdeula/

Otherwise, our own EULA must meet these terms:
http://www.apple.com/legal/itunes/appstore/dev/minterms/

**Comment by nebster** [comment]
I've read the default Apple EULA fairly closely and I think we should be OK going with it for now.  It expressly protects our use of Flurry and/or other mechanisms to gather user data, and limits our liability for damages.
