### ISSUE TITLE
write description for app store

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#112]
Maximum 4000 bytes!

e.g.

Planetary is a music player that displays your iTunes library as a 3D star system. Artists are stars, albums are planets and tracks are moons.

**Comment by RandomEtc** [comment]
Not sure if we can say "iTunes" in our app description.

It could also be a good place to list reviews (if we can find someone to review it), testimonials, links to other stuff we're doing, a little bit about Bloom, etc.  Let's check other popular app descriptions and see what they say.

**Comment by nebster** [comment]
Planetary is an all-new, stunningly beautiful way to explore your music collection, available only on iPad.  Fly through a 3D universe dynamically created by information about the recording artists you love.  Visit planets that represent your favorite albums.  And control the playback of your music on iPad by browsing and selecting astronomical objects.  Planetary is just the sort of science fiction experience you expect when using an object from the future like iPad.  You'll want to show your friends this beautiful app. We've made it even easier to share Planetary at home; it looks incredible when you hook your iPad 2 up to a big HDTV or projector using the HDMI accessory.

Planetary is the first of a new type of visual discovery app produced by Bloom Studios [http://bloom.io].  In future premium updates, look for Planetary to support playlists, browsing of friend's collections and activity, and connection to popular music streaming services.  Also in the coming months, we'll be releasing an ongoing stream of apps that let you explore and participate in social networks, video streaming services, and location-based applications in a whole new way!  We're building powerful and playful new ways to explore, understand, and communicate.  http://planetary.bloom.io
