### ISSUE TITLE
choose keywords for app store

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#113]
e.g. music, planets, space, stars, moons, ipod, itunes, player

**Comment by RandomEtc** [comment]
ipod and itunes might be verboten. what else could we add?

**Comment by RandomEtc** [comment]
planetary, bloom ?

**Comment by nebster** [comment]
aside from the good set in your first note: visualization, simulation, albums, artists, tracks, collection, constellations, galaxy...  is there a guideline for how many we should have?

**Comment by RandomEtc** [comment]
100 characters including spaces and commas, apparently. Searching for
this stuff is an SEO nightmare :)

On 14 April 2011 14:17, nebster
reply@reply.github.com
wrote:

**Comment by RandomEtc** [comment]
See also http://developer.apple.com/news/ios/pdf/ASQR_Assigning_Keywords.pdf
