### ISSUE TITLE
set up a simple web page and support page (for app store)

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#114]
App store will direct people to separate pages if we want, but they may as well be the same thing. We should make something simpler than bloom.io to ensure it's easy to load and view on the ipad :)

**Comment by RandomEtc** [comment]
e.g. planetary.bloom.io? (or a good planet domain name?)

**Comment by nebster** [comment]
i think planetary.bloom.io is good.  maybe just a nice fullscreen screenshot with a texbox overlay explaining what it is, almost like the in-app help screen?

**Comment by flight404** [comment]
Done.
