### ISSUE TITLE
PlayControls should mirror iTunes functionality

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#118]
~~If the track is 5 seconds in, hitting prev track goes back to beginning of current track.~~
If the track is the first track, hitting prev track shouldn't stop the album.

**Comment by flight404** [comment]
~~Next track when on last track should (and probably already does) stop playback.~~

**Comment by RandomEtc** [comment]
Regarding "If the track is the first track, hitting prev track shouldn't stop the album." ... sadly not possible if we want to keep getting approved in the App Store.

We can't currently access the queue without using hidden methods (we could store our own queue but we wouldn't know what was queued up if the ipod player is active when our app starts): http://www.pixiapps.com/blog/?p=78

Marking this as "wishlist" - we can revisit if Apple adds the API for this functionality.

**Comment by RandomEtc** [comment]
iOS 5 will support this: http://developer.apple.com/library/prerelease/ios/#documentation/MediaPlayer/Reference/MPMusicPlayerController_ClassReference/Reference/Reference.html%23//apple_ref/occ/instp/MPMusicPlayerController/indexOfNowPlayingItem

**Comment by RandomEtc** [comment]
Closing this as wishlist and moving to wiki. We can re-open when the time comes.
