### ISSUE TITLE
Possible funkiness with queued music in iPod immediately upon play

### ISSUE THREAD

**Issue by jandersen** [cooperhewitt/Planetary#134]
From iTunes App Store Review:

"The only surprising moment I had was when I viewed an album and hit the play button, and the music I had last been playing in the iPod app started up, instead of the album I had selected in Planetary."

**Comment by flight404** [comment]
This is a common problem. Totally based on confusing UI and not a bug.  We should make it so pressing the play button when at album level will trigger track 1 of that album.

**Comment by flight404** [comment]
Consider clearing queue on app launch (but maybe only if they navigate away from galaxy view).

**Comment by RandomEtc** [comment]
Play button should do-the-right-thing if nothing is queued, and app should start up with a letter so it should be clearer what's up.
