### ISSUE TITLE
investigate what happens if you have videos in your music library

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#142]
bug reports from Alan Costello and others seem to be resolved by removing videos from the music library.

**Comment by flight404** [comment]
Currently testing with a newly purchased copy of So+ which is the Peter Gabriel (ol Pete) So album with 5 extra music vids. The videos dont show up as option moons and so far, no crashes or weirdness at all.

**Comment by RandomEtc** [comment]
closing this, i think it's a weird edge case and nobody has mentioned it lately
