### ISSUE TITLE
use AlbumArtist property

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#148]
Tried to implement a getAlbumArtist. The thinking is that if AlbumArtist field is filled out, use that. Otherwise, use the Artist field. This will group "Bjork featuring Antony as the Conscience" into "Bjork".

**Comment by flight404** [comment]
The reason uhhh if ungh let me... .the way we currently get data is to query by artist which returns everything has an artist. If you query by albumartist, you only get things that have album artist set. We would likely need to query by track and that has its own issues.

**Comment by RandomEtc** [comment]
Closing this, it requires a total rewrite of how we get data. Maybe in a future Spotify/Rdio revamp or a desktop port, we can look at this again.
