### ISSUE TITLE
Shuffle and Repeat states

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#153]
~~Look into adding getShuffle and getRepeat or something like it to the iPodPlayer classes.~~

Also, make these work.

**Comment by RandomEtc** [comment]
Added to ipod code, needs wiring up. See also #156

**Comment by RandomEtc** [comment]
These work now, as far as I can tell. The "default" states (ie we can't know what the state is until we set it ourselves) are super annoying, but there's not a lot we can do about it.
