### ISSUE TITLE
sometimes everything disappears

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#173]
It's possible for mEye, mCenter and mCenterFrom to have nans for x and z. I haven't figured this out any further but I've seen it.

**Comment by RandomEtc** [comment]
I was dragging the playhead slider to the end of the track and holding it there.

**Comment by flight404** [comment]
Just had this happen. I went to an album. Noticed the 1st track was missing (not ghosty, completely missing) so I selected the 2nd track. When I hit prev track to go to the missing 1st track, the track played but cam went into darkness never to return. I restarted, went to same place. Track 1 was back.
