### ISSUE TITLE
Wont launch

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#179]
Have had a couple incidents where the app hangs before the loading screen even appears. If I pause the app, it shows it is at line 85 in UIController: 

while (mInterfaceAngle > 2.0f \* M_PI) mInterfaceAngle -= 2.0f \* M_PI;

I think it only happens if the app is in landscape orientation on launch.

**Comment by flight404** [comment]
When it does happen, mInterfaceAngle has a value of 9.48689e+12.

**Comment by RandomEtc** [comment]
Oh it probably needs initializing in the UIController constructor. Oops.

**Comment by flight404** [comment]
I tried setting mInterfaceAngle = 0.0f in the constructor. Still occasionally getting crazy high numbers. 7.34053e+28 is the most recent result.

**Comment by flight404** [comment]
I band-aided the situation. So far, this works fine:
if( mInterfaceAngle < ( -2.0f \* M_PI ) ){
    std::cout << "InterfaceAngle is way too low. Being adjusted" << std::endl;
    mInterfaceAngle = -2.0f \* M_PI;
} else if( mInterfaceAngle > ( 2.0f \* M_PI ) ){
    std::cout << "InterfaceAngle is way too high. Being adjusted" << std::endl;
    mInterfaceAngle = 2.0f \* M_PI;
}

**Comment by RandomEtc** [comment]
See also #178 ... I _think_ this is fixed now in the latest commit: https://github.com/bloomtime/Kepler/commit/d739ffc69dca0ab681e4ba8510da3b8408926972
