### ISSUE TITLE
app crashes if you have no playlists

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#181]
when switching to the playlists chooser.

**Comment by flight404** [comment]
Should the playlist option be _grayed_ out if no playlists are detected? Or should we find a different solution?

**Comment by RandomEtc** [comment]
I'm hiding the FilterToggleButton completely when you have no playlists. We may wish to change this if we want to entice people to add playlists and use them within Planetary, but for now it's the quickest thing that works. Shouldn't be any crashes now, since it's impossible to switch to playlist mode without the playlist toggle.
