### ISSUE TITLE
Saving data like star-rating back to itunes may not be possible.

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#21]
Ryan did a quick looksee and saw that the star rating data was read only. So, this might mean we cannot allow people to do things like set genre/rating/etc and save it back to iTunes. We could keep that data stored on the device so you will have star-rating and genre local to the device, but that might defeat the purpose of allowing people to set that at all.

**Comment by notlion** [comment]
Yeah all of the properties on MPMediaItem seem to be read only.. but it could just mean that you set it somewhere else? Then again, this is Apple we're talking about..

**Comment by flight404** [comment]
Not relevant to initial release. Also, we are considering saving local data that isn't iTunes data, like 'favorite' or 'mood', etc.
