### ISSUE TITLE
make sure all interesting assets/work-in-progress/etc are on Dropbox

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#217]

**Comment by flight404** [comment]
Added. In the Planetary folder is a new folder called RobertAssets. That has all the content I am seeing on my computer.

**Comment by RandomEtc** [comment]
Awesome, thanks for this. It's no replacement for having you around but it might help if we make it as far as an Android/iPhone/PC port, or if we want to mess with texture compression etc.
