### ISSUE TITLE
Alpha filter problem

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#223]
If you choose alpha and choose a letter, then choose playlist and select a playlist, then switch back to alpha, you cannot reselect the same letter requiring you to select a different letter then select the letter you want.

**Comment by RandomEtc** [comment]
Hmm. If you switch back to alpha then it should select the previously selected letter automatically I think. I'll look at this along with all the other filterchooser bits!

**Comment by flight404** [comment]
Had an instance of tapping a track, but having the previously selected playlist track start playing.

Ooops, closed the issue by mistake.

**Comment by RandomEtc** [comment]
Hmm, sounds like a separate issue. I've moved it to #224 because I'm about to fix the first thing :)

**Comment by RandomEtc** [comment]
OK I fixed this one. New TestFlight imminent.
