### ISSUE TITLE
Galaxy level pinch

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#227]
When I pinch at galaxy level, it triggers the FOV pop but no vignette appears. This means the edges of the galaxy can be seen. Maybe just kill the fov pinch at galaxy level if it isnt also going to trigger a filter?

**Comment by RandomEtc** [comment]
Hmm... I thought I left the vignette in, which I'd be OK with. I'll figure it out!

**Comment by RandomEtc** [comment]
Ah yeah, I see it. I know what happened. I removed the connection between wheel/vignette and playlist/alphachooser so I could restore the vignette/FOV pop, but I forgot to restore it.

**Comment by RandomEtc** [comment]
I put it back!
