### ISSUE TITLE
disable idle timer to keep screen on while playing.

### ISSUE THREAD

**Issue by jandersen** [cooperhewitt/Planetary#228]
You can disable the idle timer through the idleTimerDisabled property of the shared UIApplication object:
// Disable the idle timer
[[UIApplication sharedApplication] setIdleTimerDisabled: YES];

**Comment by RandomEtc** [comment]
Closing - is a dupe of #143 :)

Didn't do it because it seemed overly complicated in its interactions with the music library, but maybe we can get to it when we fix things up for iOS 5.

**Comment by jandersen** [comment]
excellent.
