### ISSUE TITLE
make it really obvious you should pinch when the app starts

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#24]
"pinch to begin" would be fine, if that shows the wheel

or something else, but tapping "Kepler" isn't really obvious enough

**Comment by RandomEtc** [comment]
A nice graphical icon to indicate pinching could work, something like the click instructions on https://mozillademos.org/demos/runfield/demo.html

Or something like http://gesturecons.com/ or http://gestureworks.com/features/open-source-gestures/ or http://www.lukew.com/ff/entry.asp?1071

Another alternative would be to start the app in alphawheel mode, and use the alpha wheel as a loading indicator (for the 2-10s wait while we find out the artist names).

**Comment by RandomEtc** [comment]
Or we could start the app with the wheel visible. But then how to teach people that pinching is good?

**Comment by flight404** [comment]
Need addressed.
