### ISSUE TITLE
uilayer / breadcrumbs / playcontrols should prevent taps from hitting world

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#30]
Tom can do this, it's already stubbed out in PlayControls.

**Comment by flight404** [comment]
Seems like this mostly works. There is still a possibility that touching the panel tab can trigger a node selection.

**Comment by RandomEtc** [comment]
I'm planning to revamp this a little bit more. I separated the alpha
wheel from the other UI bits to make it easier to prevent the taps and
arcball rotations affecting the world if you're dragging the uilayer.
Almost got it right, but needs another nudge.

On 16 March 2011 13:41, flight404
reply@reply.github.com
wrote:

**Comment by RandomEtc** [comment]
Done!
