### ISSUE TITLE
figure out how to use the ipad 2 gyroscope

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#56]
... to improve accelerometer interactions

probably a Cinder-level change.

**Comment by flight404** [comment]
Bill has written a quickly gyro app. Going to send me code later tonight.

**Comment by flight404** [comment]
Gyro now works, but at the sacrifice of proper arcball interaction. I can only get one or the other to work.

arcballQuat \* gyroQuat, arcball interaction is weird.
gyroQuat \* arcballQuat, gyro interaction is weird.

**Comment by RandomEtc** [comment]
I sent you a potential fix for this (using the gyro change from frame to frame to drive the arcball). Did you get a chance to try it? Any use?

**Comment by flight404** [comment]
Gyro works. Not _with_ arcball, but instead of arcball. Will have to suffice for now.
