### ISSUE TITLE
Currently playing Artist, Album, Track

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#58]
Need to find a way to keep this information around so we can do things like:
• Highlight the currently playing album orbital ring and currently playing track orbital ring after you have navigated away from the track you selected.
• scrub the playhead even when you aren't still at track level zoom.
etc

**Comment by RandomEtc** [comment]
NodeTrack has an `mIsPlaying` attribute already - does that help with the orbit ring stuff?

Perhaps we should add the same to NodeAlbum and NodeArtist - could be set in `setPlayingNode` in State.cpp using mParentNode on the given NodeTrack (and unset if needed).

I can do this if that's not making any sense :)

**Comment by RandomEtc** [comment]
...

We should set isPlaying when we make a new NodeTrack (and make sure the right thing is set in State), because sometimes we make new NodeTracks after a track has already started playing. Exciting!

**Comment by RandomEtc** [comment]
Closing this since all nodes now have `mIsPlaying` props. 

World also has `mPlayingTrackNode` that gets cached in `World::setIsPlaying` - if needed we can add `mPlayingAlbumNode` and `mPlayingArtistNode` there in the same fashion in future.
