### ISSUE TITLE
Audio player effects framerate

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#59]
Here is an interesting tidbit. Pausing the audio player in Planetary improves the framerate as much as 10 fps. On my ipad2, at album level with 12 tracks going around, the framerate is 45. If I pause the audio, it goes up to 55.

**Comment by RandomEtc** [comment]
Is that related to making new textures for the time indicator?

**Comment by flight404** [comment]
I checked, even with that whole time-texture bit turned off. Framerate still drops during audio play.

**Comment by RandomEtc** [comment]
Closing this because I don't think it's related to anything we're doing. Let's re-open if we get any bright ideas.
