### ISSUE TITLE
add Cinder BSD license credit somewhere

### ISSUE THREAD

**Issue by RandomEtc** [cooperhewitt/Planetary#68]
We probably need an "about" button hidden somewhere. BSD license states:

"Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution." -- http://www.opensource.org/licenses/bsd-license.php

We would probably get away with only having this notice on an "about" page on the app homepage, if the app links to the homepage. We probably want to do this anyway for things like mailing list signup, etc.

**Comment by flight404** [comment]
suck it.
