### ISSUE TITLE
Fix Throwable Arcball

### ISSUE THREAD

**Issue by flight404** [cooperhewitt/Planetary#7]
The arcball decelerates oddly. Perhaps find a way to lock in the current arcball axis.

**Comment by RandomEtc** [comment]
I'm pretty sure this is to do with Arcball.mouseDown and Arcball.mousePos taking Vec2i. We could try recoding those functions with Vec2f's and see if it fixes it.

**Comment by flight404** [comment]
Just tried switching to Vec2f and it seemed to have no impact on the result. I will make a throwable arcball sample and then post to the forum.

**Comment by flight404** [comment]
Two more avenues explored but both were dead ends. 1) setConstrainAxis didnt seem to have an effect. 2) Hai provided a solution but it is only for slow deliberate spins and doesnt work for fast ones.

**Comment by RandomEtc** [comment]
Here's the GLUI one I was talking about, which is LGPL: http://www.cs.uaf.edu/2006/fall/cs381/ref/glui/arcball_8h-source.html

**Comment by flight404** [comment]
Let it spin!!!
